/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.CardLayout;
import java.awt.event.ActionEvent;
import javax.swing.JPanel;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.text.AttributeSet;
import javax.swing.text.BadLocationException;
import javax.swing.text.PlainDocument;


/**
 *
 * @author David
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        menu_Panel.setVisible(true);
        GUIboard = new TableroGUI();
        GUIboard.initializeGui();
        gameBoardPanel = (JPanel) GUIboard.getGui();
        getContentPane().add(gameBoardPanel, "card4");
        player1_textf.setDocument(new JTextFieldLimit(10));
        player1_textf1.setDocument(new JTextFieldLimit(10));
        player1_textf2.setDocument(new JTextFieldLimit(10));
        player2_textf.setDocument(new JTextFieldLimit(10));
        player2_textf1.setDocument(new JTextFieldLimit(10));
        player2_textf2.setDocument(new JTextFieldLimit(10));
        player3_textf.setDocument(new JTextFieldLimit(10));
        player3_textf1.setDocument(new JTextFieldLimit(10));
        player4_textf.setDocument(new JTextFieldLimit(10));
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_Panel = new javax.swing.JPanel();
        loadGame_btn = new javax.swing.JButton();
        newGame_btn2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        newGame_panel = new javax.swing.JPanel();
        playerSelect_panel = new javax.swing.JPanel();
        cardsCombobox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        startGame_btn = new javax.swing.JButton();
        naming_panel = new javax.swing.JPanel();
        twoPlayers_panel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        player1_textf1 = new javax.swing.JTextField();
        player2_textf1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        threePlayers_panel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        player1_textf = new javax.swing.JTextField();
        player2_textf = new javax.swing.JTextField();
        player3_textf = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        fourPlayers_panel = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        player1_textf2 = new javax.swing.JTextField();
        player2_textf2 = new javax.swing.JTextField();
        player3_textf1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        player4_textf = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newGameItem = new javax.swing.JMenuItem();
        loadGameItem = new javax.swing.JMenuItem();
        saveMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        menu_Panel.setBackground(java.awt.Color.darkGray);
        menu_Panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loadGame_btn.setText("Load Game");
        menu_Panel.add(loadGame_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 100, 30));

        newGame_btn2.setText("New Game");
        newGame_btn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGame_btn2ActionPerformed(evt);
            }
        });
        menu_Panel.add(newGame_btn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 100, 30));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Snakes and ladders");
        menu_Panel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        getContentPane().add(menu_Panel, "card2");

        newGame_panel.setBackground(java.awt.Color.darkGray);
        newGame_panel.setPreferredSize(new java.awt.Dimension(400, 279));

        playerSelect_panel.setBackground(java.awt.Color.darkGray);

        cardsCombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2", "3", "4" }));
        cardsCombobox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cardsComboboxItemStateChanged(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Select the amount of players: ");

        startGame_btn.setText("Start Game");

        javax.swing.GroupLayout playerSelect_panelLayout = new javax.swing.GroupLayout(playerSelect_panel);
        playerSelect_panel.setLayout(playerSelect_panelLayout);
        playerSelect_panelLayout.setHorizontalGroup(
            playerSelect_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerSelect_panelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel7)
                .addGap(26, 26, 26)
                .addComponent(cardsCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(startGame_btn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        playerSelect_panelLayout.setVerticalGroup(
            playerSelect_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(playerSelect_panelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(playerSelect_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cardsCombobox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(startGame_btn))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        naming_panel.setLayout(new java.awt.CardLayout());

        twoPlayers_panel.setBackground(java.awt.Color.darkGray);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Player 1:");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Player 2:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Choose players names");

        javax.swing.GroupLayout twoPlayers_panelLayout = new javax.swing.GroupLayout(twoPlayers_panel);
        twoPlayers_panel.setLayout(twoPlayers_panelLayout);
        twoPlayers_panelLayout.setHorizontalGroup(
            twoPlayers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(twoPlayers_panelLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(twoPlayers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addGroup(twoPlayers_panelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(4, 4, 4)
                        .addComponent(player1_textf1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(twoPlayers_panelLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(4, 4, 4)
                        .addComponent(player2_textf1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(83, Short.MAX_VALUE))
        );
        twoPlayers_panelLayout.setVerticalGroup(
            twoPlayers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(twoPlayers_panelLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(twoPlayers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(twoPlayers_panelLayout.createSequentialGroup()
                        .addGroup(twoPlayers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(player1_textf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38))
                    .addGroup(twoPlayers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(player2_textf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        naming_panel.add(twoPlayers_panel, "card2");

        threePlayers_panel.setBackground(java.awt.Color.darkGray);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Player 3:");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Player 2:");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Player 1:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Choose players names");

        javax.swing.GroupLayout threePlayers_panelLayout = new javax.swing.GroupLayout(threePlayers_panel);
        threePlayers_panel.setLayout(threePlayers_panelLayout);
        threePlayers_panelLayout.setHorizontalGroup(
            threePlayers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(threePlayers_panelLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(threePlayers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(threePlayers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(player1_textf, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player2_textf, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player3_textf, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(72, Short.MAX_VALUE))
            .addGroup(threePlayers_panelLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        threePlayers_panelLayout.setVerticalGroup(
            threePlayers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(threePlayers_panelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel9)
                .addGap(28, 28, 28)
                .addGroup(threePlayers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player1_textf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(threePlayers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player2_textf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(threePlayers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player3_textf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );

        naming_panel.add(threePlayers_panel, "card3");

        fourPlayers_panel.setBackground(java.awt.Color.darkGray);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Player 3:");

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Player 2:");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Player 1:");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Player 4:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Choose players names");

        javax.swing.GroupLayout fourPlayers_panelLayout = new javax.swing.GroupLayout(fourPlayers_panel);
        fourPlayers_panel.setLayout(fourPlayers_panelLayout);
        fourPlayers_panelLayout.setHorizontalGroup(
            fourPlayers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fourPlayers_panelLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(fourPlayers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel13)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(fourPlayers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(player1_textf2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player2_textf2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player3_textf1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player4_textf, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );
        fourPlayers_panelLayout.setVerticalGroup(
            fourPlayers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fourPlayers_panelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addGroup(fourPlayers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player1_textf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(fourPlayers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player2_textf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fourPlayers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player3_textf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fourPlayers_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(player4_textf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );

        naming_panel.add(fourPlayers_panel, "card4");

        javax.swing.GroupLayout newGame_panelLayout = new javax.swing.GroupLayout(newGame_panel);
        newGame_panel.setLayout(newGame_panelLayout);
        newGame_panelLayout.setHorizontalGroup(
            newGame_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(naming_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(playerSelect_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        newGame_panelLayout.setVerticalGroup(
            newGame_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newGame_panelLayout.createSequentialGroup()
                .addComponent(naming_panel, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(playerSelect_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(newGame_panel, "card3");

        fileMenu.setMnemonic('f');
        fileMenu.setText("File");

        newGameItem.setText("New Game");
        newGameItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newGameItemActionPerformed(evt);
            }
        });
        fileMenu.add(newGameItem);

        loadGameItem.setText("Load Game");
        fileMenu.add(loadGameItem);

        saveMenuItem.setMnemonic('s');
        saveMenuItem.setText("Save");
        fileMenu.add(saveMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Exit");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        setJMenuBar(menuBar);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newGameItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGameItemActionPerformed
        // TODO add your handling code here:
        newGame_panel.setVisible(true);
        menu_Panel.setVisible(false);
        gameBoardPanel.setVisible(false);
    }//GEN-LAST:event_newGameItemActionPerformed

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void newGame_btn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newGame_btn2ActionPerformed
        // TODO add your handling code here:
        newGame_panel.setVisible(true);
        menu_Panel.setVisible(false);
        gameBoardPanel.setVisible(false);
    }//GEN-LAST:event_newGame_btn2ActionPerformed

    public void displayDice(int dice_value){
        GUIboard.displayDice(dice_value);
    }
    private void cardsComboboxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cardsComboboxItemStateChanged
        // TODO add your handling code here:
        CardLayout cl = (CardLayout)(naming_panel.getLayout());
        String selectedPlayers = (String)evt.getItem();
        switch(selectedPlayers){
            case "2":
                cl.show(naming_panel, "card2");
                break;
            case "3":
                cl.show(naming_panel, "card3");
                break;
            case "4":
                cl.show(naming_panel, "card4");
                break;
            default:
                break;
        }
//        if(selectedPlayers.equals("2")){
//            cl.show(naming_panel, "card2");
//        }else if(selectedPlayers.equals("4")){
//            cl.show(naming_panel, "card4");
//        }
    }//GEN-LAST:event_cardsComboboxItemStateChanged

    //metodo que escucha si se da click al boton de start game
    public void addStart_newGameListener(ActionListener listenForStartGameBtn){
        startGame_btn.addActionListener(listenForStartGameBtn);
    }
    
    public void addSave_Listener(ActionListener listenerSave){
        saveMenuItem.addActionListener(listenerSave);
    }
    
    public void addLoad_listener(ActionListener listener){
        loadGameItem.addActionListener(listener);
        loadGame_btn.addActionListener(listener);
    }
    
    public void addGameStart_listener(ActionListener listener){
        GUIboard.startButton.addActionListener(listener);
    }
    
    public void addRollDice_listener(ActionListener listener){
        GUIboard.rollDiceButton.addActionListener(listener);
    }
    public void startNewGame(){
        gameBoardPanel.setVisible(true);
        menu_Panel.setVisible(false);
        newGame_panel.setVisible(false);
    }
    
    public void displayError_message(String message){
        JOptionPane.showMessageDialog(this, message, "ERROR", HEIGHT);
    }
    
    public void setPlayersinBoardGUI(ArrayList<String> player_names){
                GUIboard.setPlayersLabels(player_names);
        
    }
    
    public ArrayList<String> getPlayersNames(){
        ArrayList<String> player_names = new ArrayList<>();
        String numberOfplayers = (String)cardsCombobox.getSelectedItem();
        switch(numberOfplayers){
            case "2":
                if((player1_textf1.getText().equals("")) || (player2_textf1.getText().equals("")) ){
                    throw new IllegalArgumentException("Must enter names for all players!");
                }else{
                    player_names.add(player1_textf1.getText());
                    player_names.add(player2_textf1.getText());
                }
                break;
            case "3":
                if((player1_textf.getText().equals("")) || (player2_textf.getText().equals("")) || (player3_textf.getText().equals("")) ){
                    throw new IllegalArgumentException("Must enter names for all players!");
                }else{
                    player_names.add(player1_textf.getText());
                    player_names.add(player2_textf.getText());
                    player_names.add(player3_textf.getText());
                }
                break;
            case "4":
                if((player1_textf2.getText().equals("")) || (player2_textf2.getText().equals("")) || (player3_textf1.getText().equals("")) ||
                                (player4_textf.getText().equals(""))){
                    throw new IllegalArgumentException("Must enter names for all players!");
                }else{
                    player_names.add(player1_textf2.getText());
                    player_names.add(player2_textf2.getText());
                    player_names.add(player3_textf1.getText());
                    player_names.add(player4_textf.getText());
                }
                break;
            default:
                break;
        }
        return  player_names;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    public void disableRollDiceButton(boolean value) {
        GUIboard.rollDiceButton.setEnabled(value);
    }
    
    

public class JTextFieldLimit extends PlainDocument {
  private int limit;

  JTextFieldLimit(int limit) {
   super();
   this.limit = limit;
   }

  public void insertString( int offset, String  str, AttributeSet attr ) throws BadLocationException {
    if (str == null) return;

    if ((getLength() + str.length()) <= limit) {
      super.insertString(offset, str, attr);
    }
  }
}

    public void displayActive_pos(int pos){
        GUIboard.displayActive_pos(pos);
    }
    
    public void setActive_playerLabel(String name){
        GUIboard.setActiveP_label(name);
    }
    public void disableGamestartbtn(){
        GUIboard.disableStart();
    }

    public TableroGUI GUIboard;
    protected javax.swing.JPanel gameBoardPanel;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cardsCombobox;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPanel fourPlayers_panel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem loadGameItem;
    private javax.swing.JButton loadGame_btn;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel menu_Panel;
    private javax.swing.JPanel naming_panel;
    private javax.swing.JMenuItem newGameItem;
    private javax.swing.JButton newGame_btn2;
    private javax.swing.JPanel newGame_panel;
    private javax.swing.JTextField player1_textf;
    private javax.swing.JTextField player1_textf1;
    private javax.swing.JTextField player1_textf2;
    private javax.swing.JTextField player2_textf;
    private javax.swing.JTextField player2_textf1;
    private javax.swing.JTextField player2_textf2;
    private javax.swing.JTextField player3_textf;
    private javax.swing.JTextField player3_textf1;
    private javax.swing.JTextField player4_textf;
    private javax.swing.JPanel playerSelect_panel;
    private javax.swing.JMenuItem saveMenuItem;
    private javax.swing.JButton startGame_btn;
    private javax.swing.JPanel threePlayers_panel;
    private javax.swing.JPanel twoPlayers_panel;
    // End of variables declaration//GEN-END:variables
}
